добавляет сетку страниц на флексах
htmlacademy-htmlcss/2379901-sedona-1 pull request #5
Opened 2024-02-19 22:13 UTC by IlmeinenLiian

2024-02-21 13:27 UTC, andreysgra requested changes
Есть ошибки валидации HTML обеих страниц. Проверьте код в валидаторе.

---

В данном проекте есть смысл сделать общую обёртку-контейнер для всего содержимого сайта: заключить в неё `header, main, footer`:
![image](https://github.com/htmlacademy-htmlcss/2379901-sedona-1/assets/17790771/5fd944e5-aab2-4e37-9456-0a386975af4a)

2024-02-21 13:27 UTC, andreysgra commented on styles/styles.css
> +  flex-direction: column;
Так как я вам предлагаю сделать общий контейнер для контента, то эти 2 свойства `display: flex; flex-direction: column;` нужно убрать у тега `body` и перенести в класс контейнера. Контейнеру понадобятся ещё три свойства: `width: 1200px` - ширина контентной области, `margin: 0 auto` - выравнивание по вертикали, `min-height: 100vh` - для создания sticky подвала.

2024-02-21 13:27 UTC, andreysgra commented on styles/styles.css
> +  margin: 0 auto;
`width` и `margin` будут о общего контейнера и здесь не понадобятся.

2024-02-21 13:27 UTC, andreysgra commented on styles/styles.css
> +}
Этот класс можно использовать для общего контейнера контентной области и добавить к нему свойство `min-heigth` про которое писал выше. Но нужно этот класс применить только к этому контейнеру, а в остальных случаях, где вы его поставили в разметке, его убрать.

2024-02-21 13:27 UTC, andreysgra commented on styles/styles.css
> +}
Ширину заголовку задавать не нужно.

2024-02-21 13:27 UTC, andreysgra commented on styles/styles.css
> +ul {
[CSS-02.](https://up.htmlacademy.ru/htmlcss-individual/1/criteries#CSS-02) Глобальный селектор.

2024-02-21 13:27 UTC, andreysgra commented on styles/styles.css
> +}
Нет необходимости в этих свойствах.

2024-02-21 13:27 UTC, andreysgra commented on styles/styles.css
> +  justify-content: space-between;
Свойство `justify-content: space-between` в блоке `.advantages-item-background` ничего не даёт, так как нет свободного пространства.

2024-02-21 13:27 UTC, andreysgra commented on styles/styles.css
> +  margin: 0;
2 лишних свойства для `.advantages-list-container`.

2024-02-21 13:27 UTC, andreysgra commented on styles/styles.css
> +  margin: 0 auto;
2 лишних свойства для `.page-footer-container`.

2024-02-21 13:27 UTC, andreysgra commented on styles/styles.css
> +  margin-right: 41.5px;
К чему такая точность? 😏 (Дробное число).

2024-02-21 13:27 UTC, andreysgra commented on styles/styles.css
> +  margin: 0 auto;
Лишние свойства для `.search`.

2024-02-21 13:27 UTC, andreysgra commented on styles/styles.css
> +  margin: 0 auto;
Лишние свойства для `.subscribe-index`.

2024-02-21 13:27 UTC, andreysgra commented on styles/styles.css
> +  width: 1200px;
Лишнее свойство для `.filter` и `.catalog-filter`.

2024-02-21 13:27 UTC, andreysgra commented on styles/styles.css
> +  width: 1200px;
Лишнее свойство для `.pagination`.

2024-02-21 13:27 UTC, andreysgra commented on styles/styles.css
> +  width: 150.43px;
Тоже ненужная точность.

2024-02-21 13:27 UTC, andreysgra commented on styles/styles.css
> +  margin: 0 auto;
Для `.hotels-list` эти 2 свойства не нужны.

2024-02-21 13:27 UTC, andreysgra commented on styles/styles.css
> +  width: 1200px;
Для `.hotels-list` это свойство не нужно.

2024-02-21 13:27 UTC, andreysgra commented on hotels.html
> +    <div class="page-container">
`<div class="page-container">` нужно убрать, так как будет общий контейнер.

2024-02-21 13:27 UTC, andreysgra commented on index.html
> +    <div class="page-container">
`<div class="page-container">` нужно убрать.

2024-02-21 21:18 UTC, IlmeinenLiian commented
У меня теперь страница отелей выглядит очень страшно)
Пока не понимаю как исправить или так и должно быть?)

2024-02-22 18:26 UTC, andreysgra requested changes
В комментарии к hotels.html я написал, что есть ошибка в разметке, но это ещё не всё. Если исследовать вёрстку в Dev Tools то можно увидеть, что каким-то образом в `div` с классом `.filter` попало всё содержимое контентной части страницы:
![image](https://github.com/htmlacademy-htmlcss/2379901-sedona-1/assets/17790771/25653c4c-5fec-4590-bd55-8a0704024222)

Поэтому вам нужно разобраться сначала с разметкой. Где-то не в том месте поставлен закрывающий тег. И обязательно проверяйте HTML через валидатор.

2024-02-22 18:26 UTC, andreysgra commented on styles/styles.css
> +  margin: 0 auto;
У `.navigation` свойства `width` и `margin` нужно убрать, так как они есть у общего контейнера `.page-container`.

2024-02-22 18:26 UTC, andreysgra commented on hotels.html
> +          </div>
Есть ошибки валидации страницы каталога. Проблема в том, что закрывающий тег `</div>` в строке 118 должен находиться не после закрывающего тега `</form>`, а перед ним.

2024-02-22 18:26 UTC, andreysgra commented on styles/styles.css
> +}
В классе `.hotels-list` добавьте свойство `flex-wrap: wrap` чтобы осуществлялся перенос флекс элементов на следующую строку.

2024-02-25 10:08 UTC, merged